#pragma once

enum http_errors_t {
    HTTPC_ERROR_CONNECTION_REFUSED,
    HTTPC_ERROR_SEND_HEADER_FAILED,
    HTTPC_ERROR_SEND_PAYLOAD_FAILED,
    HTTPC_ERROR_NOT_CONNECTED,
    HTTPC_ERROR_CONNECTION_LOST,
    HTTPC_ERROR_NO_STREAM,
    HTTPC_ERROR_NO_HTTP_SERVER,
    HTTPC_ERROR_TOO_LESS_RAM,
    HTTPC_ERROR_ENCODING,
    HTTPC_ERROR_STREAM_WRITE,
    HTTPC_ERROR_READ_TIMEOUT,
};
